- name: test playbook
  hosts: windows

  tasks:
    - name: Create DesktopUser1
      ansible.windows.win_user:
        name: DesktopUser1
        password: WGU123
        state: present
        groups:
          Administrators