- name: Create Users on Windows
  hosts: windows

  tasks:
    - name: Create DesktopUser1
      ansible.windows.win_user:
        name: DesktopUser1
        password: WGU123
        state: present
        groups:
          Administrators
    - name: Create DesktopUser2
      ansible.windows.win_user:
        name: DesktopUser2
        password: WGU123
        state: present
        groups:
          Administrators
    - name: Create DesktopUser3
      ansible.windows.win_user:
        name: DesktopUser3
        password: WGU123
        state: present
        groups:
          Administrators
    - name: Create DesktopUser4
      ansible.windows.win_user:
        name: DesktopUser4
        password: WGU123
        state: present
        groups:
          Administrators


- name: Create Users on Acct Network
  hosts: 10.10.1.56
  become: true
  tasks:
    - name: Create TestUser1
      ansible.builtin.user:
        name: TestUser1
        password: WGU123
        group: root

- name: Create Users on MGMT Network
  hosts: 10.10.1.57
  become: true
  tasks:
    - name: Create TestUser2
      ansible.builtin.user:
        name: TestUser2
        password: WGU123
        group: root