- name: Create Users on Windows
  hosts: windows

  tasks:
    - name: Create DesktopUser1
      ansible.windows.win_user:
        name: DesktopUser1
        password: WGU123
        state: present
        groups:
          Administrators
    - name: Create DesktopUser2
      ansible.windows.win_user:
        name: DesktopUser2
        password: WGU123
        state: present
        groups:
          Administrators
    - name: Create DesktopUser3
      ansible.windows.win_user:
        name: DesktopUser3
        password: WGU123
        state: present
        groups:
          Administrators
    - name: Create DesktopUser4
      ansible.windows.win_user:
        name: DesktopUser4
        password: WGU123
        state: present
        groups:
          Administrators


- name: Create Users on Acct Network
  hosts: 10.10.1.56
  become: true
  tasks:
    - name: Create TestUser1
      ansible.builtin.user:
        name: TestUser1
        password: "$6$FNOn9brrouKepnOC$rWYxdBbv9RCMTCsjpjnJRM/N1xA4Far392TNsQqkbHijON8W1RHyP4W1.TFvhuI40wUH8j/R.BJK20qSvdA4W."
        group: root

- name: Create Users on MGMT Network
  hosts: 10.10.1.57
  become: true
  tasks:
    - name: Create TestUser2
      ansible.builtin.user:
        name: TestUser2
        password: "$6$FNOn9brrouKepnOC$rWYxdBbv9RCMTCsjpjnJRM/N1xA4Far392TNsQqkbHijON8W1RHyP4W1.TFvhuI40wUH8j/R.BJK20qSvdA4W."
        group: root

- name: Create Users on Switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Create Local-Admin user
      exos_config:
        lines: create account admin test-Admin WGU123
