- name: Create Users on Switches
  hosts: switches
  tasks:
    - name: Create Local-Admin user
      community.network.exos_config:
        commands:
          - create account admin Local-Admin WGU123